/*
 * interrupt.c
 *
 *  Created on: 19/06/2026
 *      Author: felix
 */

#include"interrupt.h"

// -------------------------- Interrupt callbacks --------------------------

/**
 * @brief GPIO EXTI rising edge callback.
 *
 * Handles rising edge interrupts generated by configured GPIO pins.
 * Used for encoder updates, menu button (BOOT0), and shutter trigger control.
 *
 * @param GPIO_Pin GPIO pin number that triggered the interrupt.
 */
void HAL_GPIO_EXTI_Rising_Callback(uint16_t GPIO_Pin)
{
    static uint32_t last_button_time = 0;
    const uint32_t debounce_ms = 200; // Debounce period in milliseconds


    if (GPIO_Pin == SHUTTER_Pin)
    {
        uint32_t now = HAL_GetTick();

        // Software debounce check
        if ((now - last_button_time) >= debounce_ms)
        {
           // Interrupt code:
        	HAL_GPIO_TogglePin(LED_MCU_GPIO_Port, LED_MCU_Pin);
        }
    }
}


/**
 * @brief GPIO EXTI falling edge callback.
 *
 * Handles falling edge interrupts generated by configured GPIO pins.
 * Used for encoder updates, shutter release, and power state detection.
 *
 * @param GPIO_Pin GPIO pin number that triggered the interrupt.
 */
void HAL_GPIO_EXTI_Falling_Callback(uint16_t GPIO_Pin)
{
    // Shutter button released
    if (GPIO_Pin == SHUTTER_Pin)
    {
        //
    }
}
